---
title: "A UN Report on the Relationship between GDP and Life Expectancy"
author: "cnipit"
date: "2024-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
```
## Introduction

This is a report and it was prepared for this workshop I'm in

```{r, include=FALSE}
gapminder_1997 <- read_csv("data/gapminder_1997.csv")
```
```{r gdp_life_expectancy_1997_plot, echo=FALSE}
ggplot(data = gapminder_1997) +
  aes(x = gdpPercap, y = lifeExp, color = continent, size = pop/1e6) +
  geom_point() +
  labs(x = "GDP Per Capita", 
       y = "Life Expectancy", 
       title = "Do people in wealthy countries live longer?",
       size = "Population (in millions)")
```
```{r, include=FALSE}
nCountries <- gapminder_1997 %>% select(country) %>% n_distinct()
minGDP <- gapminder_1997 %>% summarise(round(min(gdpPercap))) %>% pull()
maxGDP <- gapminder_1997 %>% summarise(round(max(gdpPercap))) %>% pull()
```

The above plot shows the relationship between GDP per capita and life Exp for the total of `r nCountries` countries. Also minGDP `r minGDP` and maxGDP `r maxGDP`

|Summary of DATA|
|-------|-------|
|Number of Countries|`r nCountries`|
|Min of GDP per capita|`r minGDP`|
|Max of GDP per capita|`r maxGDP`|

```{r, echo=FALSE}
# load library
library(knitr)

#print kable
gapminder_1997 %>%
  filter(continent=="Oceania") %>% 
  kable()
```

